apiVersion: apps/v1
kind: Deployment
metadata: 
 name: client1
spec:
  selector: 
    matchLabels:
      role: client14ip
  template:
    metadata:
      labels:
        role: client14ip
    spec:
      serviceAccountName: build-robot
      containers:
      - name: client14
        image: angelmarques/flnetwork-registry2:latest
        env:
        - name: CLIENT_URL
          value: 'http://10.43.130.245:5000'
        - name: SERVER_URL
          value: 'http://10.43.131.165:5000'
        volumeMounts:      
        - mountPath: "/federated-learning-network/datasets"
          name: dbclient-14
        ports:
        - containerPort: 5000
      volumes: 
      - name: dbclient-14
        hostPath: 
          path: /home/dipet
      nodeName: dipet01
