apiVersion: apps/v1
kind: Deployment
metadata:
 name: client6
spec:
  selector:
    matchLabels:
      role: client19ip
  template:
    metadata:
      labels:
        role: client19ip
    spec:
      containers:
      - name: client19
        image: angelmarques/flnetwork-registry2:latest 
        env:
        - name: CLIENT_URL
          value: 'http://10.43.159.212:5000'
        - name: SERVER_URL
          value: 'http://10.43.131.165:5000'
        volumeMounts:
        - mountPath: "/federated-learning-network/datasets"
          name: dbclient-19
        ports:
        - containerPort: 5000
      volumes:
      - name: dbclient-19
        hostPath:
          path: /home/dipet
      nodeName: dipet06
