apiVersion: apps/v1
kind: Deployment
metadata:
 name: client2
spec:
  selector:
    matchLabels:
      role: client15ip
  template:
    metadata:
      labels:
        role: client15ip
    spec:
      serviceAccountName: build-robot
      containers:
      - name: client15
        image: angelmarques/flnetwork-registry2:latest 
        env:
        - name: CLIENT_URL
          value: 'http://10.43.29.252:5000'
        - name: SERVER_URL
          value: 'http://10.43.131.165:5000'
        volumeMounts:
        - mountPath: "/federated-learning-network/datasets"
          name: dbclient-15
        ports:
        - containerPort: 5000
      volumes:
      - name: dbclient-15
        hostPath:
          path: /home/dipet
      nodeName: dipet02


