apiVersion: apps/v1
kind: Deployment
metadata:
 name: client5
spec:
  selector:
    matchLabels:
      role: client18ip
  template:
    metadata:
      labels:
        role: client18ip
    spec:
      containers:
      - name: client18
        image: dkr-dsg.ac.upc.edu/tfg_angel/fl-client
        env:
        - name: CLIENT_URL
          value: 'http://10.43.3.246:5000'
        - name: SERVER_URL
          value: 'http://10.43.1.240:5000'
        volumeMounts:
        - mountPath: "/federated-learning-network/datasets"
          name: dbclient-18
        ports:
        - containerPort: 5000
      volumes:
      - name: dbclient-18
        hostPath:
          path: /home/dipet
      nodeName: dipet05
