apiVersion: apps/v1
kind: Deployment
metadata: 
 name: serverdeployment2
spec:
  selector: 
    matchLabels:
      role: serverip2
  replicas: 1
  template:
    metadata:
      labels:
        role: serverip2
    spec:
      containers:
      - name: server-02
        image: dkr-dsg.ac.upc.edu/tfg_angel/fl-server:latest
        #imagePullPolicy: Always
        ports:
        - containerPort: 5000
      nodeName: dipet00

---
apiVersion: v1
kind: Service
metadata:
  name: serviceserverip2
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    role: serverip2
