on: push
name: dockerhub_server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        registry: dkr-dsg.ac.upc.edu/harbor/tfg_angel

    - name: build, tag and push image manually 
      run: docker build -t dkr-dsg.ac.upc.edu/tfg_angel/fl-server:latest -f ./server/Dockerfile .
           docker push dkr-dsg.ac.upc.edu/tfg_angel/fl-server:latest
 
    

         
       

