on: push
name: integration
jobs: 
  integration: 
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
    - name: build image and push to harbor
      uses: docker/build-push-action@v1
      with: 
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        repository: ${{ dkr-dsg.ac.upc.edu/tfg_angel }}
        tag_with_ref: true
        tag_with_sha: true 

