on: push
name: server_integration
jobs: 
  integrationn: 
    name: deploy_server_to_cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Harbor registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        registry: dkr-dsg.ac.upc.edu/harbor/tfg_angel
    
    - name: build, tag and push image manually
      run: |
            docker build -t dkr-dsg.ac.upc.edu/tfg_angel/fl-server:latest -f ./server/Dockerfile ./server
            docker push dkr-dsg.ac.upc.edu/tfg_angel/fl-server:latest
            #docker build -t dkr-dsg.ac.upc.edu/tfg_angel/fl-client:latest -f ./client/Dockerfile ./client
            #docker push dkr-dsg.ac.upc.edu/tfg_angel/fl-client:latest
    

         
       

