on: push
name: dockerhub_server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: build, tag and push image manually 
      run: |
           docker build -t angelmarques/flnetwork-registry:latest -f ./server/Dockerfile ./server
           docker push angelmarques/flnetwork-registry:latest
           #docker build -t angelmarques/flnetwork-registry2:latest -f ./client/Dockerfile ./client
           #docker push angelmarques/flnetwork-registry2:latest

   # - uses: actions/checkout@master
   # - name: deploy to cluster
   #   uses: steebchen/kubectl@v2.0.0
   #   with: 
   #     config: ${{ secrets.KUBE_CONFIG_DATA }}
   #     command: set image --record deployment.apps/serverdeployment server-01=angelmarques/flnetwork-registry:latest
    
   # - name: verify deployment
   #   uses: steebchen/kubectl@v2.0.0
   #   with:
   #     config: ${{ secrets.KUBE_CONFIG_DATA }}
   #     version: v1.26.0
   #     binaries-url: "https://github.com/k3s-io/k3s/releases/download/v1.26.0%2Bk3s1/k3s"
   #     command: rollout status deployment.apps/serverdeployment 

    

         
       

