on: push
name: server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Harbor registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        registry: dkr-dsg.ac.upc.edu/harbor/tfg_angel
    
    - name: build image 
      uses: docker/build-push-action@v2
      with: 
        file: ./server/Dockerfile
        load: true
        tag: fl-server

    - name: running tag manually
      run: |
        docker tag fl-server dkr-dsg.ac.upc.edu/harbor/tfg_angel

    - name: running push manually
      run: |
        docker push dkr-dsg.ac.upc.edu/harbor/tfg_angel
        

         
       

