on: push
name: dockerhub_server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: build image and not push to dockerhub
      uses: docker/build-push-action@v3
      with: 
        file: ./server/Dockerfile
        push: false
        tags: fl-server

    - name: tag manually and push
      run: echo 'Done'
    

         
       

