on: push
name: dockerhub_server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: build, tag and push image manually 
      run: docker build -t angelmarques/flnetwork-registry:fl-server -f ./server/Dockerfile .
           docker push angelmarques/flnetwork-registry:fl-server
 
    

         
       

