on: push
name: server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Harbor registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}
        registry: dkr-dsg.ac.upc.edu/harbor/tfg_angel
    
    - name: build image and push to harbor
      uses: docker/build-push-action@v1
      with: 
        path: /server
        push: true
        tags: fl-server
        tag_with_ref: true
        tag_with_sha: true 
       

