on: push
name: dockerhub_server_integration
jobs: 
  integration: 
    name: deploy_server_to_cluster_dockerhub
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo 
      uses: actions/checkout@master
    
    - name: Login to Docker registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWD }}

    - name: build, tag and push image manually 
      run: |
           docker build -t angelmarques/flnetwork-registry:latest -f ./server/Dockerfile ./server
           docker push angelmarques/flnetwork-registry:latest

    - name: deploy to cluster
      uses: steebchen/kubectl@master
      env: 
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}  
      with:
        args: set image --record deployment.apps/serverdeployment server-01=angelmarques/flnetwork-registry:latest

    - name: verify deployment
      uses: steebchen/kubectl@master
      env: 
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.25.4"
      with:
        args: '"rollout status deployment.apps/serverdeployment"' 

    

         
       

